name: test

permissions: read-all

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: stable

      - run: go mod download
      - run: go fmt ./...
      - run: go vet ./...
      - run: go test ./... -coverprofile=coverage.out
